// Code generated by MockGen. DO NOT EDIT.
// Source: core.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryManager is a mock of RepositoryManager interface.
type MockRepositoryManager struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryManagerMockRecorder
}

// MockRepositoryManagerMockRecorder is the mock recorder for MockRepositoryManager.
type MockRepositoryManagerMockRecorder struct {
	mock *MockRepositoryManager
}

// NewMockRepositoryManager creates a new mock instance.
func NewMockRepositoryManager(ctrl *gomock.Controller) *MockRepositoryManager {
	mock := &MockRepositoryManager{ctrl: ctrl}
	mock.recorder = &MockRepositoryManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryManager) EXPECT() *MockRepositoryManagerMockRecorder {
	return m.recorder
}

// EnsureRepositoriesEnabled mocks base method.
func (m *MockRepositoryManager) EnsureRepositoriesEnabled() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureRepositoriesEnabled")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureRepositoriesEnabled indicates an expected call of EnsureRepositoriesEnabled.
func (mr *MockRepositoryManagerMockRecorder) EnsureRepositoriesEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureRepositoriesEnabled", reflect.TypeOf((*MockRepositoryManager)(nil).EnsureRepositoriesEnabled))
}
