// Code generated by MockGen. DO NOT EDIT.
// Source: dnf.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	api "github.com/mizdebsk/rhel-drivers/internal/api"
)

// MockPackageManager is a mock of PackageManager interface.
type MockPackageManager struct {
	ctrl     *gomock.Controller
	recorder *MockPackageManagerMockRecorder
}

// MockPackageManagerMockRecorder is the mock recorder for MockPackageManager.
type MockPackageManagerMockRecorder struct {
	mock *MockPackageManager
}

// NewMockPackageManager creates a new mock instance.
func NewMockPackageManager(ctrl *gomock.Controller) *MockPackageManager {
	mock := &MockPackageManager{ctrl: ctrl}
	mock.recorder = &MockPackageManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageManager) EXPECT() *MockPackageManagerMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockPackageManager) Install(packages []string, batchMode, dryRun bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", packages, batchMode, dryRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockPackageManagerMockRecorder) Install(packages, batchMode, dryRun interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockPackageManager)(nil).Install), packages, batchMode, dryRun)
}

// ListAvailablePackages mocks base method.
func (m *MockPackageManager) ListAvailablePackages() ([]api.PackageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailablePackages")
	ret0, _ := ret[0].([]api.PackageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailablePackages indicates an expected call of ListAvailablePackages.
func (mr *MockPackageManagerMockRecorder) ListAvailablePackages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailablePackages", reflect.TypeOf((*MockPackageManager)(nil).ListAvailablePackages))
}

// ListInstalledPackages mocks base method.
func (m *MockPackageManager) ListInstalledPackages() ([]api.PackageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstalledPackages")
	ret0, _ := ret[0].([]api.PackageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstalledPackages indicates an expected call of ListInstalledPackages.
func (mr *MockPackageManagerMockRecorder) ListInstalledPackages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstalledPackages", reflect.TypeOf((*MockPackageManager)(nil).ListInstalledPackages))
}

// Remove mocks base method.
func (m *MockPackageManager) Remove(packages []string, batchMode, dryRun bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", packages, batchMode, dryRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockPackageManagerMockRecorder) Remove(packages, batchMode, dryRun interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockPackageManager)(nil).Remove), packages, batchMode, dryRun)
}
